In [5]:
import pandas as pd
import numpy as np
import warnings 
import matplotlib.pyplot as plt
import seaborn as sns
warnings.filterwarnings("ignore")

In [6]:
df = pd.read_csv("wav2vec2_embeddings.csv")

In [7]:
df1 = pd.read_csv("CODA_TB_Clinical_Meta_Info.csv")

In [8]:
df.head()

,filename,feat_0,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,...,feat_758,feat_759,feat_760,feat_761,feat_762,feat_763,feat_764,feat_765,feat_766,feat_767
0,1637846163058-recording-1_modclean_A_seg0.wav,-0.026476,0.066998,-0.026330,-0.012994,-0.140130,-0.121104,0.082295,-0.000749,-0.034801,...,0.178794,-0.059214,0.042189,0.375900,-0.115341,-0.003523,-0.013059,-0.097548,0.011164,0.045216
1,1637846163058-recording-1_modclean_B_seg0.wav,-0.115683,0.074489,0.014545,-0.005770,-0.184433,-0.109778,0.070073,-0.004235,-0.051047,...,0.199888,-0.057528,0.064345,0.192314,-0.074626,-0.005368,-0.018542,-0.167560,0.044945,0.045402
2,1637846854303-recording-1_modclean_B_seg0.wav,-0.036963,0.027261,-0.097449,-0.025534,-0.055059,-0.135565,0.002773,-0.035429,-0.032010,...,0.197761,-0.059905,-0.086376,0.191788,-0.106577,-0.000759,-0.021116,-0.055957,0.054928,0.021372
3,1637846855223-recording-1_modclean_A_seg0.wav,-0.066899,0.018125,-0.133178,-0.038802,-0.032812,-0.119408,-0.008754,-0.031919,-0.104976,...,0.206694,-0.057743,-0.038637,0.032180,-0.114743,-0.003052,-0.019576,-0.012964,0.037439,0.004577
4,1637846855223-recording-1_modclean_B_seg0.wav,-0.032680,0.024876,-0.140349,-0.030479,0.017331,-0.111734,-0.022145,-0.028799,-0.051605,...,0.207966,-0.060599,-0.056256,0.093473,-0.156570,0.000502,-0.019766,0.013757,0.057933,0.031120

In [9]:
df1.head()

,participant,sex,age,height,weight,reported_cough_dur,tb_prior,tb_prior_Pul,tb_prior_Extrapul,tb_prior_Unknown,hemoptysis,heart_rate,temperature,weight_loss,smoke_lweek,fever,night_sweats,tb_status
0,CODA_TB_0001,Male,27,173.3,63.0,30,No,No,No,No,No,99,37.2,Yes,No,Yes,Yes,0
1,CODA_TB_0002,Female,48,163.0,49.9,16,Yes,Yes,No,No,No,80,36.6,Yes,No,No,Yes,1
2,CODA_TB_0003,Male,51,165.0,58.0,14,Yes,No,Yes,No,No,100,37.0,Yes,No,No,No,0
3,CODA_TB_0004,Male,32,166.0,56.0,90,No,No,No,No,No,90,37.0,Yes,No,No,Yes,0
4,CODA_TB_0005,Male,28,170.5,53.0,14,No,No,No,No,No,94,36.0,No,No,No,Yes,0

In [10]:
df.columns

Index(['filename', 'feat_0', 'feat_1', 'feat_2', 'feat_3', 'feat_4', 'feat_5',
       'feat_6', 'feat_7', 'feat_8',
       ...
       'feat_758', 'feat_759', 'feat_760', 'feat_761', 'feat_762', 'feat_763',
       'feat_764', 'feat_765', 'feat_766', 'feat_767'],
      dtype='object', length=769)

In [11]:
df1.columns

Index(['participant', 'sex', 'age', 'height', 'weight', 'reported_cough_dur',
       'tb_prior', 'tb_prior_Pul', 'tb_prior_Extrapul', 'tb_prior_Unknown',
       'hemoptysis', 'heart_rate', 'temperature', 'weight_loss', 'smoke_lweek',
       'fever', 'night_sweats', 'tb_status'],
      dtype='object')